run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    # Linters that were previously in 'formatters'
    - gofumpt
    - goimports

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    # Updated to match your provider's module name
    local-prefixes: github.com/easytofu/terraform-provider-pingoneprovisioning
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude specific directories from linting
  exclude-dirs:
    - third_party
    - builtin
    - examples

  # Specific rule exclusions
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
      text: "always receives"