run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # REMOVED: modules-download-mode: vendor (This caused the CI failure)

linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    # Linters moved from formatters
    - gofumpt
    - goimports

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    # Matches your module name
    local-prefixes: github.com/easytofu/terraform-provider-pingoneprovisioning
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - third_party
    - builtin
    - examples

  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
      text: "always receives"