# /.goreleaser.yml
# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2

env:
  - COSIGN_YES=true

before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy

builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      # FIX: Windows on 32-bit ARM is not a supported target for most providers
      - goos: windows
        goarch: arm
    binary: "{{ .ProjectName }}"

archives:
  - formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  extra_files:
    - glob: "terraform-registry-manifest.json"
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  # GPG: Signs the checksum file with your private key (Required for Terraform Registry).
  - id: gpg
    cmd: gpg
    signature: "${artifact}.sig" # Explicitly force .sig extension for Terraform Registry
    args:
      - --batch
      - --pinentry-mode=loopback
      - --passphrase-fd=0
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    # FIX: Pass the env var into GPG's stdin so it doesn't hang waiting for a prompt
    stdin: "{{ .Env.GPG_PASSPHRASE }}"
    artifacts: checksum

release:
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

changelog:
  disable: true
